[versions]
kotlin = "2.2.21"
compose-bom = "2025.11.00"
firebase-bom = "34.6.0"
play-services-auth = "21.4.0"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.17.0" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.9.4" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.11.0" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }

firebase-auth = { module = "com.google.firebase:firebase-auth-ktx" }

play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "play-services-auth" }

androidx-test-junit = { module = "androidx.test.ext:junit", version = "1.3.0" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version = "3.7.0" }

androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }

mockito-core = { module = "org.mockito:mockito-core", version = "5.20.0" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version = "6.1.0" }
junit = { group = "junit", name = "junit", version = "4.13.2" }



[plugins]
android-application = { id = "com.android.application", version = "8.13.1" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
googleServices = { id = "com.google.gms.google-services", version = "4.4.4" }
